# Đặt thư mục gốc của project (thường là thư mục chứa file go.mod)
root = "."

# Đường dẫn đến thư mục tạm để Air lưu trữ các file biên dịch tạm thời
tmp_dir = "tmp"

# Cấu hình build
[build]
  # Đường dẫn đến file biên dịch tạm thời. Air sẽ tạo một file biên dịch ở đây.
  # Đây là nơi chứa file kết quả khi biên dịch chương trình.
  bin = "tmp/main"

  # Lệnh chạy dự án. Air sẽ sử dụng lệnh này để chạy ứng dụng mỗi khi có thay đổi.
  # Trong trường hợp này, ứng dụng sẽ được chạy từ file `cmd/server/main.go`
  cmd = "go run cmd/server/main.go"

  # Các thư mục hoặc file sẽ được theo dõi để Air reload khi có sự thay đổi.
  # "." là thư mục gốc, có nghĩa là Air sẽ theo dõi tất cả các thay đổi trong project.
  include = ["."]
  
  # Các thư mục hoặc file sẽ bị loại trừ khỏi việc theo dõi.
  # Thường là các thư mục tạm như "tmp" hay "vendor" vì chúng không cần thiết phải theo dõi.
  exclude = ["tmp", "vendor"]

  # Các flag bổ sung cho lệnh biên dịch Go (nếu cần).
  # Trong trường hợp này, nó chỉ định tag `dev`, thường dùng cho các cấu hình đặc biệt.
  flags = ["-tags=dev"]

# Cấu hình log
[log]
  # Thêm timestamp vào log để dễ dàng theo dõi thời gian xảy ra sự kiện.
  time = true

  # Chỉnh màu sắc của log. Bạn có thể tùy chọn màu sắc cho dễ nhìn.
  color = "cyan"
